/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRoomsRouteImport } from './routes/_app.rooms'
import { Route as AppReservationsRouteImport } from './routes/_app.reservations'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRatesRouteImport } from './routes/_app.rates'
import { Route as AppPosRouteImport } from './routes/_app.pos'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppIdentityRouteImport } from './routes/_app.identity'
import { Route as AppHrRouteImport } from './routes/_app.hr'
import { Route as AppHousekeepingRouteImport } from './routes/_app.housekeeping'
import { Route as AppGuestsRouteImport } from './routes/_app.guests'
import { Route as AppEventsRouteImport } from './routes/_app.events'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCheckOutRouteImport } from './routes/_app.check-out'
import { Route as AppCheckInRouteImport } from './routes/_app.check-in'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAccountingRouteImport } from './routes/_app.accounting'
import { Route as AppReservationsNewRouteImport } from './routes/_app.reservations.new'
import { Route as AppPosOrdersRouteImport } from './routes/_app.pos.orders'
import { Route as AppPosMenuRouteImport } from './routes/_app.pos.menu'
import { Route as AppInventoryRequisitionsRouteImport } from './routes/_app.inventory.requisitions'
import { Route as AppInventoryPurchaseOrdersRouteImport } from './routes/_app.inventory.purchase-orders'
import { Route as AppInventoryListRouteImport } from './routes/_app.inventory.list'
import { Route as AppHrScheduleRouteImport } from './routes/_app.hr.schedule'
import { Route as AppHrProfileRouteImport } from './routes/_app.hr.profile'
import { Route as AppHrPayrollRouteImport } from './routes/_app.hr.payroll'
import { Route as AppHrLeavesRouteImport } from './routes/_app.hr.leaves'
import { Route as AppEventsNewRouteImport } from './routes/_app.events.new'
import { Route as AppEventsListRouteImport } from './routes/_app.events.list'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsRoute = AppReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRatesRoute = AppRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppIdentityRoute = AppIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppHousekeepingRoute = AppHousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => AppRoute,
} as any)
const AppGuestsRoute = AppGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckOutRoute = AppCheckOutRouteImport.update({
  id: '/check-out',
  path: '/check-out',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckInRoute = AppCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsNewRoute = AppReservationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppReservationsRoute,
} as any)
const AppPosOrdersRoute = AppPosOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppPosRoute,
} as any)
const AppPosMenuRoute = AppPosMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppPosRoute,
} as any)
const AppInventoryRequisitionsRoute =
  AppInventoryRequisitionsRouteImport.update({
    id: '/requisitions',
    path: '/requisitions',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryPurchaseOrdersRoute =
  AppInventoryPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryListRoute = AppInventoryListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppHrScheduleRoute = AppHrScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrProfileRoute = AppHrProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrPayrollRoute = AppHrPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrLeavesRoute = AppHrLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AppHrRoute,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppEventsRoute,
} as any)
const AppEventsListRoute = AppEventsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AppEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accounting': typeof AppAccountingRoute
  '/audit': typeof AppAuditRoute
  '/billing': typeof AppBillingRoute
  '/check-in': typeof AppCheckInRoute
  '/check-out': typeof AppCheckOutRoute
  '/dashboard': typeof AppDashboardRoute
  '/events': typeof AppEventsRouteWithChildren
  '/guests': typeof AppGuestsRoute
  '/housekeeping': typeof AppHousekeepingRoute
  '/hr': typeof AppHrRouteWithChildren
  '/identity': typeof AppIdentityRoute
  '/inventory': typeof AppInventoryRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/pos': typeof AppPosRouteWithChildren
  '/rates': typeof AppRatesRoute
  '/reports': typeof AppReportsRoute
  '/reservations': typeof AppReservationsRouteWithChildren
  '/rooms': typeof AppRoomsRoute
  '/settings': typeof AppSettingsRoute
  '/events/list': typeof AppEventsListRoute
  '/events/new': typeof AppEventsNewRoute
  '/hr/leaves': typeof AppHrLeavesRoute
  '/hr/payroll': typeof AppHrPayrollRoute
  '/hr/profile': typeof AppHrProfileRoute
  '/hr/schedule': typeof AppHrScheduleRoute
  '/inventory/list': typeof AppInventoryListRoute
  '/inventory/purchase-orders': typeof AppInventoryPurchaseOrdersRoute
  '/inventory/requisitions': typeof AppInventoryRequisitionsRoute
  '/pos/menu': typeof AppPosMenuRoute
  '/pos/orders': typeof AppPosOrdersRoute
  '/reservations/new': typeof AppReservationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accounting': typeof AppAccountingRoute
  '/audit': typeof AppAuditRoute
  '/billing': typeof AppBillingRoute
  '/check-in': typeof AppCheckInRoute
  '/check-out': typeof AppCheckOutRoute
  '/dashboard': typeof AppDashboardRoute
  '/events': typeof AppEventsRouteWithChildren
  '/guests': typeof AppGuestsRoute
  '/housekeeping': typeof AppHousekeepingRoute
  '/hr': typeof AppHrRouteWithChildren
  '/identity': typeof AppIdentityRoute
  '/inventory': typeof AppInventoryRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/pos': typeof AppPosRouteWithChildren
  '/rates': typeof AppRatesRoute
  '/reports': typeof AppReportsRoute
  '/reservations': typeof AppReservationsRouteWithChildren
  '/rooms': typeof AppRoomsRoute
  '/settings': typeof AppSettingsRoute
  '/events/list': typeof AppEventsListRoute
  '/events/new': typeof AppEventsNewRoute
  '/hr/leaves': typeof AppHrLeavesRoute
  '/hr/payroll': typeof AppHrPayrollRoute
  '/hr/profile': typeof AppHrProfileRoute
  '/hr/schedule': typeof AppHrScheduleRoute
  '/inventory/list': typeof AppInventoryListRoute
  '/inventory/purchase-orders': typeof AppInventoryPurchaseOrdersRoute
  '/inventory/requisitions': typeof AppInventoryRequisitionsRoute
  '/pos/menu': typeof AppPosMenuRoute
  '/pos/orders': typeof AppPosOrdersRoute
  '/reservations/new': typeof AppReservationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/accounting': typeof AppAccountingRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/check-in': typeof AppCheckInRoute
  '/_app/check-out': typeof AppCheckOutRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/events': typeof AppEventsRouteWithChildren
  '/_app/guests': typeof AppGuestsRoute
  '/_app/housekeeping': typeof AppHousekeepingRoute
  '/_app/hr': typeof AppHrRouteWithChildren
  '/_app/identity': typeof AppIdentityRoute
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/pos': typeof AppPosRouteWithChildren
  '/_app/rates': typeof AppRatesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/reservations': typeof AppReservationsRouteWithChildren
  '/_app/rooms': typeof AppRoomsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/events/list': typeof AppEventsListRoute
  '/_app/events/new': typeof AppEventsNewRoute
  '/_app/hr/leaves': typeof AppHrLeavesRoute
  '/_app/hr/payroll': typeof AppHrPayrollRoute
  '/_app/hr/profile': typeof AppHrProfileRoute
  '/_app/hr/schedule': typeof AppHrScheduleRoute
  '/_app/inventory/list': typeof AppInventoryListRoute
  '/_app/inventory/purchase-orders': typeof AppInventoryPurchaseOrdersRoute
  '/_app/inventory/requisitions': typeof AppInventoryRequisitionsRoute
  '/_app/pos/menu': typeof AppPosMenuRoute
  '/_app/pos/orders': typeof AppPosOrdersRoute
  '/_app/reservations/new': typeof AppReservationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/sitemap.xml'
    | '/accounting'
    | '/audit'
    | '/billing'
    | '/check-in'
    | '/check-out'
    | '/dashboard'
    | '/events'
    | '/guests'
    | '/housekeeping'
    | '/hr'
    | '/identity'
    | '/inventory'
    | '/notifications'
    | '/pos'
    | '/rates'
    | '/reports'
    | '/reservations'
    | '/rooms'
    | '/settings'
    | '/events/list'
    | '/events/new'
    | '/hr/leaves'
    | '/hr/payroll'
    | '/hr/profile'
    | '/hr/schedule'
    | '/inventory/list'
    | '/inventory/purchase-orders'
    | '/inventory/requisitions'
    | '/pos/menu'
    | '/pos/orders'
    | '/reservations/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/sitemap.xml'
    | '/accounting'
    | '/audit'
    | '/billing'
    | '/check-in'
    | '/check-out'
    | '/dashboard'
    | '/events'
    | '/guests'
    | '/housekeeping'
    | '/hr'
    | '/identity'
    | '/inventory'
    | '/notifications'
    | '/pos'
    | '/rates'
    | '/reports'
    | '/reservations'
    | '/rooms'
    | '/settings'
    | '/events/list'
    | '/events/new'
    | '/hr/leaves'
    | '/hr/payroll'
    | '/hr/profile'
    | '/hr/schedule'
    | '/inventory/list'
    | '/inventory/purchase-orders'
    | '/inventory/requisitions'
    | '/pos/menu'
    | '/pos/orders'
    | '/reservations/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/sitemap.xml'
    | '/_app/accounting'
    | '/_app/audit'
    | '/_app/billing'
    | '/_app/check-in'
    | '/_app/check-out'
    | '/_app/dashboard'
    | '/_app/events'
    | '/_app/guests'
    | '/_app/housekeeping'
    | '/_app/hr'
    | '/_app/identity'
    | '/_app/inventory'
    | '/_app/notifications'
    | '/_app/pos'
    | '/_app/rates'
    | '/_app/reports'
    | '/_app/reservations'
    | '/_app/rooms'
    | '/_app/settings'
    | '/_app/events/list'
    | '/_app/events/new'
    | '/_app/hr/leaves'
    | '/_app/hr/payroll'
    | '/_app/hr/profile'
    | '/_app/hr/schedule'
    | '/_app/inventory/list'
    | '/_app/inventory/purchase-orders'
    | '/_app/inventory/requisitions'
    | '/_app/pos/menu'
    | '/_app/pos/orders'
    | '/_app/reservations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rooms': {
      id: '/_app/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations': {
      id: '/_app/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AppReservationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rates': {
      id: '/_app/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof AppRatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/identity': {
      id: '/_app/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof AppIdentityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr': {
      id: '/_app/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/housekeeping': {
      id: '/_app/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof AppHousekeepingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guests': {
      id: '/_app/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof AppGuestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/check-out': {
      id: '/_app/check-out'
      path: '/check-out'
      fullPath: '/check-out'
      preLoaderRoute: typeof AppCheckOutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/check-in': {
      id: '/_app/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof AppCheckInRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting': {
      id: '/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations/new': {
      id: '/_app/reservations/new'
      path: '/new'
      fullPath: '/reservations/new'
      preLoaderRoute: typeof AppReservationsNewRouteImport
      parentRoute: typeof AppReservationsRoute
    }
    '/_app/pos/orders': {
      id: '/_app/pos/orders'
      path: '/orders'
      fullPath: '/pos/orders'
      preLoaderRoute: typeof AppPosOrdersRouteImport
      parentRoute: typeof AppPosRoute
    }
    '/_app/pos/menu': {
      id: '/_app/pos/menu'
      path: '/menu'
      fullPath: '/pos/menu'
      preLoaderRoute: typeof AppPosMenuRouteImport
      parentRoute: typeof AppPosRoute
    }
    '/_app/inventory/requisitions': {
      id: '/_app/inventory/requisitions'
      path: '/requisitions'
      fullPath: '/inventory/requisitions'
      preLoaderRoute: typeof AppInventoryRequisitionsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/purchase-orders': {
      id: '/_app/inventory/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/inventory/purchase-orders'
      preLoaderRoute: typeof AppInventoryPurchaseOrdersRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/list': {
      id: '/_app/inventory/list'
      path: '/list'
      fullPath: '/inventory/list'
      preLoaderRoute: typeof AppInventoryListRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/hr/schedule': {
      id: '/_app/hr/schedule'
      path: '/schedule'
      fullPath: '/hr/schedule'
      preLoaderRoute: typeof AppHrScheduleRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/profile': {
      id: '/_app/hr/profile'
      path: '/profile'
      fullPath: '/hr/profile'
      preLoaderRoute: typeof AppHrProfileRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/payroll': {
      id: '/_app/hr/payroll'
      path: '/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof AppHrPayrollRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/leaves': {
      id: '/_app/hr/leaves'
      path: '/leaves'
      fullPath: '/hr/leaves'
      preLoaderRoute: typeof AppHrLeavesRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/events/new': {
      id: '/_app/events/new'
      path: '/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppEventsRoute
    }
    '/_app/events/list': {
      id: '/_app/events/list'
      path: '/list'
      fullPath: '/events/list'
      preLoaderRoute: typeof AppEventsListRouteImport
      parentRoute: typeof AppEventsRoute
    }
  }
}

interface AppEventsRouteChildren {
  AppEventsListRoute: typeof AppEventsListRoute
  AppEventsNewRoute: typeof AppEventsNewRoute
}

const AppEventsRouteChildren: AppEventsRouteChildren = {
  AppEventsListRoute: AppEventsListRoute,
  AppEventsNewRoute: AppEventsNewRoute,
}

const AppEventsRouteWithChildren = AppEventsRoute._addFileChildren(
  AppEventsRouteChildren,
)

interface AppHrRouteChildren {
  AppHrLeavesRoute: typeof AppHrLeavesRoute
  AppHrPayrollRoute: typeof AppHrPayrollRoute
  AppHrProfileRoute: typeof AppHrProfileRoute
  AppHrScheduleRoute: typeof AppHrScheduleRoute
}

const AppHrRouteChildren: AppHrRouteChildren = {
  AppHrLeavesRoute: AppHrLeavesRoute,
  AppHrPayrollRoute: AppHrPayrollRoute,
  AppHrProfileRoute: AppHrProfileRoute,
  AppHrScheduleRoute: AppHrScheduleRoute,
}

const AppHrRouteWithChildren = AppHrRoute._addFileChildren(AppHrRouteChildren)

interface AppInventoryRouteChildren {
  AppInventoryListRoute: typeof AppInventoryListRoute
  AppInventoryPurchaseOrdersRoute: typeof AppInventoryPurchaseOrdersRoute
  AppInventoryRequisitionsRoute: typeof AppInventoryRequisitionsRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryListRoute: AppInventoryListRoute,
  AppInventoryPurchaseOrdersRoute: AppInventoryPurchaseOrdersRoute,
  AppInventoryRequisitionsRoute: AppInventoryRequisitionsRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppPosRouteChildren {
  AppPosMenuRoute: typeof AppPosMenuRoute
  AppPosOrdersRoute: typeof AppPosOrdersRoute
}

const AppPosRouteChildren: AppPosRouteChildren = {
  AppPosMenuRoute: AppPosMenuRoute,
  AppPosOrdersRoute: AppPosOrdersRoute,
}

const AppPosRouteWithChildren =
  AppPosRoute._addFileChildren(AppPosRouteChildren)

interface AppReservationsRouteChildren {
  AppReservationsNewRoute: typeof AppReservationsNewRoute
}

const AppReservationsRouteChildren: AppReservationsRouteChildren = {
  AppReservationsNewRoute: AppReservationsNewRoute,
}

const AppReservationsRouteWithChildren = AppReservationsRoute._addFileChildren(
  AppReservationsRouteChildren,
)

interface AppRouteChildren {
  AppAccountingRoute: typeof AppAccountingRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCheckInRoute: typeof AppCheckInRoute
  AppCheckOutRoute: typeof AppCheckOutRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEventsRoute: typeof AppEventsRouteWithChildren
  AppGuestsRoute: typeof AppGuestsRoute
  AppHousekeepingRoute: typeof AppHousekeepingRoute
  AppHrRoute: typeof AppHrRouteWithChildren
  AppIdentityRoute: typeof AppIdentityRoute
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPosRoute: typeof AppPosRouteWithChildren
  AppRatesRoute: typeof AppRatesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReservationsRoute: typeof AppReservationsRouteWithChildren
  AppRoomsRoute: typeof AppRoomsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountingRoute: AppAccountingRoute,
  AppAuditRoute: AppAuditRoute,
  AppBillingRoute: AppBillingRoute,
  AppCheckInRoute: AppCheckInRoute,
  AppCheckOutRoute: AppCheckOutRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEventsRoute: AppEventsRouteWithChildren,
  AppGuestsRoute: AppGuestsRoute,
  AppHousekeepingRoute: AppHousekeepingRoute,
  AppHrRoute: AppHrRouteWithChildren,
  AppIdentityRoute: AppIdentityRoute,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPosRoute: AppPosRouteWithChildren,
  AppRatesRoute: AppRatesRoute,
  AppReportsRoute: AppReportsRoute,
  AppReservationsRoute: AppReservationsRouteWithChildren,
  AppRoomsRoute: AppRoomsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
