/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRoomsRouteImport } from './routes/_app.rooms'
import { Route as AppReservationsRouteImport } from './routes/_app.reservations'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPosRouteImport } from './routes/_app.pos'
import { Route as AppHousekeepingRouteImport } from './routes/_app.housekeeping'
import { Route as AppGuestsRouteImport } from './routes/_app.guests'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppReservationsNewRouteImport } from './routes/_app.reservations.new'
import { Route as AppPosOrdersRouteImport } from './routes/_app.pos.orders'
import { Route as AppPosMenuRouteImport } from './routes/_app.pos.menu'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsRoute = AppReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppHousekeepingRoute = AppHousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => AppRoute,
} as any)
const AppGuestsRoute = AppGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsNewRoute = AppReservationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppReservationsRoute,
} as any)
const AppPosOrdersRoute = AppPosOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppPosRoute,
} as any)
const AppPosMenuRoute = AppPosMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppPosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/guests': typeof AppGuestsRoute
  '/housekeeping': typeof AppHousekeepingRoute
  '/pos': typeof AppPosRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/reservations': typeof AppReservationsRouteWithChildren
  '/rooms': typeof AppRoomsRoute
  '/settings': typeof AppSettingsRoute
  '/pos/menu': typeof AppPosMenuRoute
  '/pos/orders': typeof AppPosOrdersRoute
  '/reservations/new': typeof AppReservationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/guests': typeof AppGuestsRoute
  '/housekeeping': typeof AppHousekeepingRoute
  '/pos': typeof AppPosRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/reservations': typeof AppReservationsRouteWithChildren
  '/rooms': typeof AppRoomsRoute
  '/settings': typeof AppSettingsRoute
  '/pos/menu': typeof AppPosMenuRoute
  '/pos/orders': typeof AppPosOrdersRoute
  '/reservations/new': typeof AppReservationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/guests': typeof AppGuestsRoute
  '/_app/housekeeping': typeof AppHousekeepingRoute
  '/_app/pos': typeof AppPosRouteWithChildren
  '/_app/reports': typeof AppReportsRoute
  '/_app/reservations': typeof AppReservationsRouteWithChildren
  '/_app/rooms': typeof AppRoomsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/pos/menu': typeof AppPosMenuRoute
  '/_app/pos/orders': typeof AppPosOrdersRoute
  '/_app/reservations/new': typeof AppReservationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/billing'
    | '/dashboard'
    | '/guests'
    | '/housekeeping'
    | '/pos'
    | '/reports'
    | '/reservations'
    | '/rooms'
    | '/settings'
    | '/pos/menu'
    | '/pos/orders'
    | '/reservations/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/billing'
    | '/dashboard'
    | '/guests'
    | '/housekeeping'
    | '/pos'
    | '/reports'
    | '/reservations'
    | '/rooms'
    | '/settings'
    | '/pos/menu'
    | '/pos/orders'
    | '/reservations/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/sitemap.xml'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/guests'
    | '/_app/housekeeping'
    | '/_app/pos'
    | '/_app/reports'
    | '/_app/reservations'
    | '/_app/rooms'
    | '/_app/settings'
    | '/_app/pos/menu'
    | '/_app/pos/orders'
    | '/_app/reservations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rooms': {
      id: '/_app/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations': {
      id: '/_app/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AppReservationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/housekeeping': {
      id: '/_app/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof AppHousekeepingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guests': {
      id: '/_app/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof AppGuestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations/new': {
      id: '/_app/reservations/new'
      path: '/new'
      fullPath: '/reservations/new'
      preLoaderRoute: typeof AppReservationsNewRouteImport
      parentRoute: typeof AppReservationsRoute
    }
    '/_app/pos/orders': {
      id: '/_app/pos/orders'
      path: '/orders'
      fullPath: '/pos/orders'
      preLoaderRoute: typeof AppPosOrdersRouteImport
      parentRoute: typeof AppPosRoute
    }
    '/_app/pos/menu': {
      id: '/_app/pos/menu'
      path: '/menu'
      fullPath: '/pos/menu'
      preLoaderRoute: typeof AppPosMenuRouteImport
      parentRoute: typeof AppPosRoute
    }
  }
}

interface AppPosRouteChildren {
  AppPosMenuRoute: typeof AppPosMenuRoute
  AppPosOrdersRoute: typeof AppPosOrdersRoute
}

const AppPosRouteChildren: AppPosRouteChildren = {
  AppPosMenuRoute: AppPosMenuRoute,
  AppPosOrdersRoute: AppPosOrdersRoute,
}

const AppPosRouteWithChildren =
  AppPosRoute._addFileChildren(AppPosRouteChildren)

interface AppReservationsRouteChildren {
  AppReservationsNewRoute: typeof AppReservationsNewRoute
}

const AppReservationsRouteChildren: AppReservationsRouteChildren = {
  AppReservationsNewRoute: AppReservationsNewRoute,
}

const AppReservationsRouteWithChildren = AppReservationsRoute._addFileChildren(
  AppReservationsRouteChildren,
)

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGuestsRoute: typeof AppGuestsRoute
  AppHousekeepingRoute: typeof AppHousekeepingRoute
  AppPosRoute: typeof AppPosRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppReservationsRoute: typeof AppReservationsRouteWithChildren
  AppRoomsRoute: typeof AppRoomsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGuestsRoute: AppGuestsRoute,
  AppHousekeepingRoute: AppHousekeepingRoute,
  AppPosRoute: AppPosRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppReservationsRoute: AppReservationsRouteWithChildren,
  AppRoomsRoute: AppRoomsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
